accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    # Te endpointy powinny być w aplikacji account
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login_view'),
    path('logout/', views.logout_view, name='logout_view'),

    # Te endpointy powinny być w innej aplikacji (bo nie dotyczą modelu użytkownika)
    # ale zostawiamy je tutaj, żeby tematy związane z uwierzytelnieniem i autoryzacją
    # były obok siebie.
    path('home/', views.home, name='home'),
    path('fun/', views.fun_view, name='test_view'),
    path('secret/', views.secret_view, name='secret_view'),
]

intro/urls.py
from django.contrib import admin
from django.urls import path, include

from helo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', views.hello),
    path('jurek/', views.jurek),
    path('hi/', views.hi),
    path('hi2/', views.hi2),

    path('next/', include('next_app.urls')),
    path('links/', include('links.urls')),
    path('inheritance/', include('inheritance.urls')),
    path('form/', include('form_app.urls')),
    path('form2/', include('form_app2.urls')),
    path('form3/', include('form_app3.urls')),
    path('form4/', include('form_app4.urls')),
    path('form5/', include('form_app5.urls')),
    path('crud/', include('crud_app.urls')),
    path('relations/', include('relations_app.urls')),
    path('message/', include('message_app.urls')),
    path('view/', include('view_app.urls')),
    path('state/', include('state_app.urls')),
    path('auth/', include('auth_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('dogs/', include('api_app.urls')),
]

accounts/models.py
from django.db import models

from django.contrib.auth import models


# Create your models here.
class User(models.AbstractUser):
    pass

accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import authenticate, login, logout


User = get_user_model()


@login_required(login_url='accounts:login_view')
def home(request):
    return render(
        request,
        'accounts/home.html',
    )


def register_view(request):
    if request.method == "GET":
        return render(
            request,
            'accounts/register.html',
        )
    else:
        data = request.POST
        username = data.get('username')
        password1 = data.get('password1')
        password2 = data.get('password2')

        if password1 == password2:
            User.objects.create_user(
                username=username,
                password=password1
            )

        return redirect('accounts:login_view')


def login_view(request):
    if request.method == "GET":
        return render(
            request,
            'accounts/login.html'
        )
    elif request.method == "POST":
        data = request.POST
        username = data.get('username')
        password = data.get('password')

        user = authenticate(
            username=username,
            password=password
        )
        if user:
            login(request, user=user)

        return redirect('accounts:home')


def logout_view(request):
    logout(request)

    return redirect('accounts:home')


def fun_view(request):
    return render(
        request,
        'accounts/fun.html'
    )


@permission_required('accounts.view_user', raise_exception=True)
def secret_view(request):
    return render(
        request,
        'accounts/secret.html'
    )

accounts/templates/accounts/fun.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <img src="{% static 'accounts/img/cat.webp' %}">

  {% if perms.accounts.change_user %}
    <button>Tylko wybrańcy mogą to zrobić</button>
  {% endif %}

</body>
</html>

accounts/templates/accounts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--  {% if user.is_authenticated %}-->
    <h2>Witaj {{ user }}!</h2>
    <a href="{% url 'accounts:logout_view' %}"><button>Wyloguj</button></a>
<!--  {% else %}-->
<!--     <a href="{% url 'accounts:login_view' %}"><button>Zaloguj</button></a>-->
<!--  {% endif %}-->
</body>
</html>

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form method="POST">{% csrf_token %}
      <input type=text name="username" placeholder="username">
      <input type="password" name="password" placeholder="password">
      <input type="submit" value="Zaloguj">
  </form>
</body>
</html>

accounts/templates/accounts/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <form method="POST">{% csrf_token %}
    <input type="text" name="username" placeholder="username">
    <input type="password" name="password1" placeholder="password">
    <input type="password" name="password2" placeholder="password">
    <input type="submit" value="Zarejestruj">
  </form>
</body>
</html>

accounts/templates/accounts/secret.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    Super tajne!
</body>
</html>